######################## Configuration par défaut ####################

# Thème
theme: "dot-org-hugo-theme"

# Titre du site
title: "Centre des Loisirs de Fatima"

# Fuseau horaire
timeZone: "Canada/Atlantic"

# Longueur des résumés
summaryLength: 50

######################## Multilinguisme ####################

# Langue par défaut
defaultContentLanguage: fr

# IMPORTANT: Mettre les langues dans des sous-répertoires (/fr/ et /en/)
# Cela évite les conflits d'URLs et facilite la gestion
defaultContentLanguageInSubdir: true

######################## Confidentialité ####################

privacy:
  youtube:
    privacyEnhanced: true
  vimeo:
    enableDNT: true

######################## Rendu ####################

markup:
  goldmark:
    renderer:
      unsafe: true
