fr:
  languageName: Français
  weight: 1
  title: "Centre des Loisirs de Fatima"
  copyright: "Copyright © 2026 LE CENTRE DES LOISIRS DE FATIMA, Î.M., INC. Tous droits réservés."
  params:
    description: "Description du site"
    accessibility:
      skip_text: "Aller au contenu"
      help_text: "Déclaration d'accessibilité"
      help_url: "/fr/contact/"
    main_cta:
      text: "Nous joindre"
      link: "/fr/contact/"
    footer_cta:
      text: "Nous joindre"
      link: "/fr/contact/"
    github_edit: "Modifier cette page sur GitHub"
  menu:
    main:
      - identifier: "accueil"
        name: "Accueil"
        url: "/fr/"
        weight: 1
      - identifier: "joker"
        name: "Joker"
        url: ""
        weight: 2
      - identifier: "comment-jouer"
        name: "Comment jouer"
        url: "/fr/joker/comment-jouer/"
        parent: "joker"
        weight: 1
      - identifier: "points-de-vente"
        name: "Points de vente"
        url: "/fr/joker/points-de-vente/"
        parent: "joker"
        weight: 2
      - identifier: "joker-gagnants"
        name: "Gagnants"
        url: "/fr/joker/gagnants/"
        parent: "joker"
        weight: 3
      - identifier: "reglements"
        name: "Règlements"
        url: "/fr/joker/reglements/"
        parent: "joker"
        weight: 4
      - identifier: "activites"
        name: "Activités"
        url: ""
        weight: 3
      - identifier: "activites-a-venir"
        name: "Activités à venir"
        url: "/fr/activites/activites-a-venir/"
        parent: "activites"
        weight: 1
      - identifier: "activites-passees"
        name: "Activités passées"
        url: "/fr/activites/activites-passees/"
        parent: "activites"
        weight: 2
      - identifier: "gallerie-photos"
        name: "Galerie Photos"
        url: "/fr/activites/gallerie-photos/"
        parent: "activites"
        weight: 3
      - identifier: "projets"
        name: "Projets"
        url: "/fr/projets/"
        weight: 4
      - identifier: "en-cours"
        name: "Projets en cours"
        url: "/fr/projets/en-cours/"
        parent: "projets"
        weight: 1
      - identifier: "passes"
        name: "Projets passés"
        url: "/fr/projets/passes/"
        parent: "projets"
        weight: 2
      - identifier: "contact"
        name: "Contact"
        url: ""
        weight: 5
      - identifier: "nous-joindre"
        name: "Nous joindre"
        url: "/fr/contact/nous-joindre/"
        parent: "contact"
        weight: 1
      - identifier: "notre_equipe"
        name: "Notre équipe"
        url: "/fr/contact/notre-equipe/"
        parent: "contact"
        weight: 2
      - identifier: "reservations"
        name: "Réservations"
        url: "/fr/contact/reservations/"
        parent: "contact"
        weight: 3
en:
  languageName: English
  contentDir: content/en
  weight: 2
  title: "Centre des Loisirs de Fatima"
  copyright: "Copyright © 2026 LE CENTRE DES LOISIRS DE FATIMA, Î.M., INC. All rights reserved."
  params:
    description: "Site Description"
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/en/contact/"
    main_cta:
      text: "Contact us"
      link: "/en/contact/"
    footer_cta:
      text: "Contact us"
      link: "/en/contact/"
    github_edit: "Edit this page on GitHub"
  menu:
    main:
      - identifier: "home"
        name: "Home"
        url: "/en/"
        weight: 1
      - identifier: "joker"
        name: "Joker"
        url: ""
        weight: 2
      - identifier: "how-to-play"
        name: "How to play"
        url: "/en/joker/how-to-play/"
        parent: "joker"
        weight: 1
      - identifier: "points-of-sale"
        name: "Points of sale"
        url: "/en/joker/points-of-sale/"
        parent: "joker"
        weight: 2
      - identifier: "winners"
        name: "Winners"
        url: "/en/joker/winners/"
        parent: "joker"
        weight: 3
      - identifier: "rules"
        name: "Rules"
        url: "/en/joker/rules/"
        parent: "joker"
        weight: 4
      - identifier: "activities"
        name: "Activities"
        url: ""
        weight: 3
      - identifier: "upcoming-activities"
        name: "Upcoming activities"
        url: "/en/activities/upcoming-activities/"
        parent: "activities"
        weight: 1
      - identifier: "past-activities"
        name: "Past activities"
        url: "/en/activities/past-activities/"
        parent: "activities"
        weight: 2
      - identifier: "photo-gallery"
        name: "Photo gallery"
        url: "/en/activities/photo-gallery/"
        parent: "activities"
        weight: 3
      - identifier: "projects"
        name: "Projects"
        url: "/en/projects/"
        weight: 4
      - identifier: "ongoing-projects"
        name: "Ongoing projects"
        url: "/en/projects/ongoing/"
        parent: "projects"
        weight: 1
      - identifier: "past-projects"
        name: "Past projects"
        url: "/en/projects/past/"
        parent: "projects"
        weight: 2
      - identifier: "contact"
        name: "Contact"
        url: ""
        weight: 5
      - identifier: "contact-us"
        name: "Contact us"
        url: "/en/contact/contact-us/"
        parent: "contact"
        weight: 1
      - identifier: "our-team"
        name: "Our team"
        url: "/en/contact/our-team/"
        parent: "contact"
        weight: 2
      - identifier: "reservations"
        name: "Reservations"
        url: "/en/contact/reservations/"
        parent: "contact"
        weight: 3