fr:
  languageName: Français
  weight: 1
  title: "Centre des Loisirs de Fatima"
  params:
    description: "Description du site"
    accessibility:
      skip_text: "Aller au contenu"
      help_text: "Déclaration d'accessibilité"
      help_url: "/fr/contact/"
    main_cta:
      text: "Nous joindre"
      link: "/fr/contact/"
    footer_cta:
      text: "Nous joindre"
      link: "/fr/contact/"
    github_edit: "Modifier cette page sur GitHub"
  menu:
    main:
      - identifier: "accueil"
        name: "Accueil"
        url: "/fr/"
        weight: 1
      - identifier: "joker"
        name: "Joker"
        url: ""
        weight: 2
      - identifier: "comment-jouer"
        name: "Comment jouer"
        url: "/fr/joker/comment-jouer/"
        parent: "joker"
        weight: 1
      - identifier: "points-de-vente"
        name: "Points de vente"
        url: "/fr/joker/points-de-vente/"
        parent: "joker"
        weight: 2
      - identifier: "joker-gagnants"
        name: "Gagnants"
        url: "/fr/joker/gagnants/"
        parent: "joker"
        weight: 3
      - identifier: "reglements"
        name: "Règlements"
        url: "/fr/joker/reglements/"
        parent: "joker"
        weight: 4
      - identifier: "activites"
        name: "Activités"
        url: ""
        weight: 3
      - identifier: "activites-a-venir"
        name: "Activités à venir"
        url: "/fr/activites/activites-a-venir/"
        parent: "activites"
        weight: 1
      - identifier: "activites-passees"
        name: "Activités passées"
        url: "/fr/activites/activites-passees/"
        parent: "activites"
        weight: 2
      - identifier: "gallerie-photos"
        name: "Galerie Photos"
        url: "/fr/activites/gallerie-photos/"
        parent: "activites"
        weight: 3
      - identifier: "projets"
        name: "Projets"
        url: "/fr/projets/"
        weight: 4
      - identifier: "en-cours"
        name: "Projets en cours"
        url: "/fr/projets/en-cours/"
        parent: "projets"
        weight: 1
      - identifier: "passes"
        name: "Projets passés"
        url: "/fr/projets/passes/"
        parent: "projets"
        weight: 2
      - identifier: "contact"
        name: "Contact"
        url: ""
        weight: 5
      - identifier: "nous-joindre"
        name: "Nous joindre"
        url: "/fr/contact/nous-joindre/"
        parent: "contact"
        weight: 1
      - identifier: "notre_equipe"
        name: "Notre équipe"
        url: "/fr/contact/notre-equipe/"
        parent: "contact"
        weight: 2
      - identifier: "reservations"
        name: "Réservations"
        url: "/fr/contact/reservations/"
        parent: "contact"
        weight: 3
en:
  languageName: English
  contentDir: content/en
  weight: 2
  title: "Site Title"
  params:
    description: "Site Description"
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/en/about/"
    main_cta:
      text: "Join"
      link: "/en/about/"
    footer_cta:
      text: "Join us"
      link: "/en/about/"
    github_edit: "Edit this page on GitHub"
  menu:
    main:
      - identifier: "about"
        name: "About"
        url: "/en/about/"
        weight: 1
      - identifier: "faq"
        name: "FAQs"
        url: "/en/faq/"
        weight: 2
      - identifier: "blog"
        name: "Blog"
        url: "/en/blog/"
        weight: 3