######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "img/Logo.png"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/Logo.png"]

github:
  repo_url: "https://github.com/miamoto15/centreloisirsdefatima"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: "https://www.facebook.com/profile.php?id=61558108406588"
  flickr: ""
  github: "https://github.com/miamoto15/centreloisirsdefatima"
  instagram: ""
  landscape: ""
  linkedin: ""
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false
