name: Auto approve PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'miamoto15' # remplace par ton nom d'utilisateur si diff√©rent
    steps:
      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN_BOT }}
